# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
---
- name: remove opnsense plugins
  ansible.builtin.command:
    cmd: "/usr/local/opnsense/scripts/firmware/launcher.sh remove {{ item }}"
    removes: "/usr/local/opnsense/version/{{ item | split('-', 1) | last }}"
  with_items: "{{ opn_plugins_remove }}"
  loop_control:
    pause: "{{ opn_plugpack_sleep }}"
  register: opnsense_plugpack__register_remove_opnsense_plugins

- name: give the process some time for settling ...
  ansible.builtin.pause:
    seconds: "{{ opn_plugpack_sleep }}"
  when: opnsense_plugpack__register_remove_opnsense_plugins.changed # noqa no-handler

- name: install opnsense plugins
  ansible.builtin.command:
    cmd: "/usr/local/opnsense/scripts/firmware/launcher.sh install {{ item }}"
    creates: "/usr/local/opnsense/version/{{ item | split('-', 1) | last }}"
  with_items: "{{ opn_plugins | default([]) }}"
  loop_control:
    pause: "{{ opn_plugpack_sleep }}"
  register: opnsense_plugpack__register_install_opnsense_plugins

- name: give the process some time for settling ...
  ansible.builtin.pause:
    seconds: "{{ opn_plugpack_sleep }}"
  when: opnsense_plugpack__register_install_opnsense_plugins.changed # noqa no-handler

- name: purge opnsense pkg
  community.general.pkgng:
    name: "{{ opn_packages_remove }}"
    state: absent
  register: opnsense_plugpack__register_purge_opnsense_pkg

- name: give the process some time for settling ...
  ansible.builtin.pause:
    seconds: "{{ opn_plugpack_sleep }}"
  when: opnsense_plugpack__register_purge_opnsense_pkg.changed # noqa no-handler

- name: install opnsense pkg
  community.general.pkgng:
    name: "{{ opn_packages }}"
    state: present

...
